name: calendar_scheduler
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: 3.0.9
  intl: 0.18.1
  uuid: 4.1.0
  firebase_core: 2.19.0
  cloud_firestore: 4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
