name: random_dice
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shake: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  sensors_plus_platform_interface: 1.1.3

flutter:
  uses-material-design: true
  assets:
    - asset/img/
